Reverting to working version: cb68036225be6e09b5888eae1a7c408821d65afe

diff --git a/freenas/9.10-tests/delete/cronjob b/freenas/9.10-tests/delete/cronjob
--- a/freenas/9.10-tests/delete/cronjob
+++ b/freenas/9.10-tests/delete/cronjob
@@ -15,22 +15,30 @@ cronjob_tests() {
   TESTFILE="/tmp/.testFileUpdatedViaCronjob"
   CRONJOB_ID=1
 
-  # Ensure test file does not exist
-  echo_test_title "Verify cronjob has been removed and is no longer creating test file.."
-  ssh_test 'test -f '${TESTFILE}'; test $? -eq 1'
-  check_exit_status || return 1
-
   # Delete cronjob from API
   echo_test_title "Deleting cron job which will run every minute"
   rest_request "DELETE" "/tasks/cronjob/${CRONJOB_ID}/"
-  check_rest_response "204" || return 1
+  check_rest_response "204"
 
   # Check that cronjob was deleted from API
   echo_test_title "Check that the API reports the cronjob as deleted.."
   rest_request "GET" "/tasks/cronjob/${CRONJOB_ID}/"
-  check_rest_response "404" || return 1
+  check_rest_response "404"
 
-  return 0
+  # Clean up test file now that the cronjob has been removed
+  ssh_test "rm -f ${TESTFILE}"
+
+  # Give time for cronjob to run again, then ensure no file was created
+  sleep 61
+
+  # Ensure test file does not exist
+  echo_test_title "Verify cronjob has been removed and is no longer creating test file.."
+  ssh_test 'test -f '${TESTFILE}'; test $? -eq 1'
+  if [ $? -eq 0 ]; then
+    echo_ok
+  else
+    echo_failed
+  fi
 }
 
 # Init function, this is called after module is sourced
