Add more tests to AD.

diff --git a/freenas/9.3-tests/ad b/freenas/9.3-tests/ad
--- a/freenas/9.3-tests/ad
+++ b/freenas/9.3-tests/ad
@@ -10,18 +10,40 @@ REQUIRES="storage"
 export REQUIRES
 
 ad_tests() {
-  set_test_group_text "Active Directory tests" "1"
+  set_test_group_text "Active Directory tests" "5"
 
-  if [ -z "$ADUSERNAME" -o -z "$ADPASSWORD" -o -z "$ADNETBIOSNAME" -o -z "$ADREALM" ] ; then
-     echo "Missing the ADUSERNAME / ADPASSWORD / ADNETBIOSNAME / ADREALM settings, test skipped.."
+  if [ -z "$ADUSERNAME" -o -z "$ADPASSWORD" -o -z "$ADNETBIOSNAME_A" -o -z "$ADREALM" -o -z "$ADNTPSERVER" ] ; then
+     echo "Missing the ADUSERNAME / ADPASSWORD / ADNETBIOSNAME / ADREALM / ADNTPSERVER settings, test skipped.."
      echo_skipped
      add_xml_result "skipped" "Skipped due to missing AD settings"
   fi
 
+  # Update NTP Settings
+  echo_test_title "Updating NTP Settings for AD.."
+  rest_request "PUT" /system/ntpserver/1/ '{ "id": "1", "ntp_address": "'${ADNTPSERVER}'", "ntp_burse": "true", "ntp_iburst": "true", "ntp_maxpoll": "10", "ntp_minpoll": "6", "ntp_prefer": "true", "pk": "1" }'
+  check_rest_response "200 OK" || return 1
 
-  # Join the Active Directory
+  # Update Active Directory Settings
   echo_test_title "Updating Settings for AD.."
   rest_request "PUT" "/directoryservice/activedirectory/" '{ "ad_bindpw": "'${ADPASSWORD}'", "ad_bindname": "'${ADUSERNAME}'", "ad_netbiosname": "${ADNETBIOSNAME}", "ad_domainname": "'${ADREALM}'" }'
+  check_rest_response "200 OK" || return 1
+
+
+  # Enable Active Directory
+  echo_test_title "Enabling Active Directory.."
+  rest_request "PUT" "/directoryservice/activedirectory/" '{ "ad_enable": "true", "ad_netbiosname_a": "'${ADNETBIOSNAME_A}'" }'
+  check_rest_response "200 OK" || return 1
+
+
+  # Check Active Directory
+  echo_test_title "Checking Active Directory.."
+  rest_request GET "/directoryservice/activedirectory/" | jsawk 'return this.ad_enable'
+  check_rest_response "200 OK" || return 1
+
+
+  # Disable Active Directory
+  echo_test_title "Disabling Active Directory.."
+  rest_request "PUT" "/directoryservice/activedirectory/" '{ "ad_enable": "false", "ad_netbiosname_a": "'{ADNETBIOSNAME_A}'" }'
   check_rest_response "200 OK" || return 1
 
 }
