Add some cleanup to AFP tests

diff --git a/freenas/9.10-tests/create/afp b/freenas/9.10-tests/create/afp
--- a/freenas/9.10-tests/create/afp
+++ b/freenas/9.10-tests/create/afp
@@ -23,6 +23,11 @@ afp_tests()
     osx_test 'umount -f "/Volumes/'"${BRIDGEHOST}"'"; rmdir "/Volumes/'"${BRIDGEHOST}"'"; exit 0'
   fi
 
+  # Clean up any leftover items from previous failed runs
+  rest_request "PUT" "/services/afp/" '{ "afp_srv_guest": false }'
+  rest_request "DELETE" "/sharing/afp/" '{ "afp_name": "'"${AFP_SHARE}"'", "afp_path": "/mnt/tank/afp" }'
+  rest_request "DELETE" "/storage/volume/1/datasets/afp/"
+
   # Set the group text and number of tests
   set_test_group_text "1 - Create - AFP tests" "${TESTS_CNT}"
   CLASSNAME=ixbuild.resty.functional.create.afp
@@ -78,6 +83,16 @@ afp_tests()
     osx_test 'umount -f "/Volumes/'"${BRIDGEHOST}"'"'
     check_exit_status || return 1
   fi
+
+  # Test disable AFP
+  echo_test_title "Verify AFP service can be disabled.."
+  rest_request "PUT" "/services/afp/" '{ "afp_srv_guest": false }'
+  check_rest_response "200 OK" || return 1
+
+  # Test delete AFP dataset
+  echo_test_title "Verify AFP dataset can be destroyed.."
+  rest_request "DELETE" "/storage/volume/1/datasets/afp/"
+  check_rest_response "204" || return 1
 
   return 0
 }
diff --git a/freenas/9.10-tests/update/afp b/freenas/9.10-tests/update/afp
--- a/freenas/9.10-tests/update/afp
+++ b/freenas/9.10-tests/update/afp
@@ -23,13 +23,47 @@ afp_tests()
     osx_test 'umount -f "/Volumes/'"${BRIDGEHOST}"'"; rmdir "/Volumes/'"${BRIDGEHOST}"'"; exit 0'
   fi
 
+  # Clean up any leftover items from previous failed runs
+  rest_request "PUT" "/services/afp/" '{ "afp_srv_guest": false }'
+  rest_request "DELETE" "/sharing/afp/" '{ "afp_name": "'"${AFP_SHARE}"'", "afp_path": "/mnt/tank/afp" }'
+  rest_request "DELETE" "/storage/volume/1/datasets/afp/"
+
   # Set the group text and number of tests
   set_test_group_text "2 - Update - AFP tests" "${TEST_CNT}"
   CLASSNAME=ixbuild.resty.functional.update.afp
 
+  echo_test_title "Creating AFP dataset"
+  rest_request "PUT" "/storage/permission/" '{ "mp_path": "'${AFP_PATH}'", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
+  check_rest_response "201 Created" || return 1
+
   echo_test_title "Updating AFP service"
   rest_request "PUT" "/services/afp/" '{ "afp_srv_connections_limit": "100"  }'
   check_rest_response "200" || return 1
+
+  echo_test_title "Enabling AFP service"
+  if [ -z "${BRIDGEIP}" ]; then
+    rest_request "PUT" "/services/afp/" '{ "afp_srv_guest": true, "afp_srv_bindip": "'"${BRIDGEIP}"'" }'
+  else
+    rest_request "PUT" "/services/afp/" '{ "afp_srv_guest": true }'
+  fi
+  check_rest_response "200 OK" || return 1
+
+  echo_test_title "Creating a AFP share on /mnt/tank/afp"
+  rest_request "POST" "/sharing/afp/" '{ "afp_name": "'"${AFP_SHARE}"'", "afp_path": "/mnt/tank/afp" }'
+  check_rest_response "201 Created" || return 1
+
+  # Now start the service
+  echo_test_title "Starting AFP service"
+  rest_request "PUT" "/services/services/afp/" '{ "srv_enable": true }'
+  check_rest_response "200 OK" || return 1
+
+  echo_test_title "Checking to see if AFP service is enabled"
+  rest_request "GET" "/services/services/afp/"
+  check_service_status "RUNNING" || return 1
+
+  echo_test_title "Changing permissions on ${AFP_PATH}"
+  rest_request "PUT" "/storage/permission/" '{ "mp_path": "'${AFP_PATH}'", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "wheel" }'
+  check_rest_response "201 Created" || return 1
 
   echo_test_title "Checking to see if AFP service is enabled"
   rest_request "GET" "/services/services/afp/"
@@ -57,6 +91,18 @@ afp_tests()
     osx_test 'umount "/Volumes/'"${BRIDGEHOST}"'"'
     check_exit_status || return 1
   fi  
+
+  # Test disable AFP
+  echo_test_title "Verify AFP service can be disabled.."
+  rest_request "PUT" "/services/afp/" '{ "afp_srv_guest": false }'
+  check_rest_response "200 OK" || return 1
+
+  # Test delete AFP dataset
+  echo_test_title "Verify AFP dataset can be destroyed.."
+  rest_request "DELETE" "/storage/volume/1/datasets/afp/"
+  check_rest_response "204" || return 1
+
+  return 0
 }
 
 # Init function, this is called after module is sourced
