Re-applying pre-master-merge devel changes.

diff --git a/freenas/9.10-tests/create/afp_osx b/freenas/9.10-tests/create/afp_osx
--- a/freenas/9.10-tests/create/afp_osx
+++ b/freenas/9.10-tests/create/afp_osx
@@ -14,26 +14,27 @@ afp_osx_tests()
   set_test_group_text "1 - Create - AFP OS X tests" "20"
   CLASSNAME=ixbuild.resty.functional.create.afp_osx
 
+  local REQUIRED_SETTINGS=( "BRIDGEIP" "OSX_HOST" )
+  for SETTING in "${REQUIRED_SETTINGS[@]}"
+  do  
+    if [ -z "${!SETTING}" ]; then
+      echo -n "Required settings for afp_osx: '${REQUIRED_SETTINGS[*]}'; missing ${SETTING}"
+      echo_skipped
+      return 0
+    fi  
+  done
+
   local DATASET="afp-osx"
   local AFP_NAME="My AFP Share"
   local AFP_PATH="/mnt/tank/${DATASET}"
-  local MOUNTPOINT="/tmp/afp-osx${BRIDGEHOST}"
+  local MOUNTPOINT="/tmp/${BRIDGEHOST}afp-osx"
   local MP_GROUP="qa"
-
-  # Set the test count based on config settings
-  TESTS_CNT="14"
-  if [ -n "${OSX_HOST}" -a -n "${BRIDGEIP}" ]; then
-    TESTS_CNT="18"
-
-    # Clean up any leftover items from previous failed AFP runs
-    osx_test "umount -f '${MOUNTPOINT}'; rmdir '${MOUNTPOINT}'; exit 0;"
-  fi
 
   # Clean up any leftover items from previous failed runs
   rest_request "PUT" "/services/afp/" '{ "afp_srv_guest": false }'
   rest_request "DELETE" "/sharing/afp/" '{ "afp_name": "'"${AFP_NAME}"'", "afp_path": "'"${AFP_PATH}"'" }'
   rest_request "DELETE" "/storage/volume/1/datasets/${DATASET}/"
-  osx_test -q "diskutil unmount force \"${MOUNTPOINT}\"; rmdir \"${MOUNTPOINT}\"; exit 0;"
+  osx_test "diskutil unmount force \"${MOUNTPOINT}\"; rmdir \"${MOUNTPOINT}\""
 
   echo_test_title "Creating AFP dataset"
   rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "'"${DATASET}"'" }'
@@ -74,37 +75,45 @@ afp_osx_tests()
 
   # Mount share on OSX system and create a test file
   echo_test_title "Create mount-point for AFP on OSX system"
-  osx_test "mkdir -p '${MOUNTPOINT}' && sync" || return 1
+  osx_test "mkdir -p '${MOUNTPOINT}' && sync"
+  check_exit_status || return 1
 
   echo_test_title "Mount AFP share on OSX system"
-  osx_test "mount -t afp 'afp://${BRIDGEIP}/${AFP_NAME}' '${MOUNTPOINT}'" || return 1
+  osx_test "mount -t afp 'afp://${BRIDGEIP}/${AFP_NAME}' '${MOUNTPOINT}'"
+  check_exit_status || return 1
 
   echo_test_title "Verify AFP share has been mounted on OSX"
   wait_for_osx_mnt "${MOUNTPOINT}"
   check_exit_status || return 1
 
   echo_test_title "Checking for ability to list files on ${MOUNTPOINT}"
-  osx_test "time ls -la ${MOUNTPOINT}" || return 1
+  osx_test "time ls -la ${MOUNTPOINT}"
+  check_exit_status || return 1
 
   echo_test_title "Create file on AFP share via OSX to test permissions"
-  osx_test "touch '${MOUNTPOINT}/testfile.txt'" || return 1
+  osx_test "touch '${MOUNTPOINT}/testfile.txt'"
+  check_exit_status || return 1
 
   # Move test file to a new location on the AFP share
   echo_test_title "Moving AFP test file into a new directory"
-  osx_test "mkdir -p '${MOUNTPOINT}/tmp' && mv '${MOUNTPOINT}/testfile.txt' '${MOUNTPOINT}/tmp/testfile.txt'" || return 1
+  osx_test "mkdir -p '${MOUNTPOINT}/tmp' && mv '${MOUNTPOINT}/testfile.txt' '${MOUNTPOINT}/tmp/testfile.txt'"
+  check_exit_status || return 1
 
   # Delete test file and test directory from AFP share
   echo_test_title "Deleting test file and directory from AFP share"
-  osx_test "rm -f '${MOUNTPOINT}/tmp/testfile.txt' && rmdir '${MOUNTPOINT}/tmp'" || return 1
+  osx_test "rm -f '${MOUNTPOINT}/tmp/testfile.txt' && rmdir '${MOUNTPOINT}/tmp'"
+  check_exit_status || return 1
 
   echo_test_title "Verifying that test file and directory were successfully removed"
-  osx_test "find -- '${MOUNTPOINT}/' -prune -type d -empty | grep -q ." || return 1
+  osx_test "find -- '${MOUNTPOINT}/' -prune -type d -empty | grep -q ."
+  check_exit_status || return 1
 
   # Clean up mounted AFP share
   # OS X `umount` manpage reports that umount may fail often.
   # "It is recommended that diskutil(1) (as in, ``diskutil unmount /mnt'') be used instead."
   echo_test_title "Unmount AFP share"
-  osx_test "diskutil unmount force '${MOUNTPOINT}'" || return 1
+  osx_test "diskutil unmount force '${MOUNTPOINT}'"
+  check_exit_status || return 1
 
   # Test disable AFP
   echo_test_title "Verify AFP service can be disabled.."
