Check iscsitarget with srv_state, clean up after any previous failures if any.

diff --git a/freenas/9.10-tests/create/iscsi b/freenas/9.10-tests/create/iscsi
--- a/freenas/9.10-tests/create/iscsi
+++ b/freenas/9.10-tests/create/iscsi
@@ -12,8 +12,13 @@ export REQUIRES
 iscsi_tests()
 {
   # Set the group text and number of tests
-  set_test_group_text "1 - Create - iSCSI tests" "16"
+  set_test_group_text "1 - Create - iSCSI tests" "19"
   CLASSNAME=ixbuild.resty.functional.create.iscsi
+
+  # Clean up any leftover items from any previous failed runs
+  rest_request "PUT" "/services/services/iscsitarget/" '{ "srv_enable": "false" }'
+  rc_test "iscsictl -R -a" || return 1
+  rc_test "umount -A" || return 1
 
   # Add iSCSI initator
   echo_test_title "Add iSCSI initiator"
@@ -49,6 +54,18 @@ iscsi_tests()
   echo_test_title "Enable iSCSI service"
   rest_request "PUT" "/services/services/iscsitarget/" '{ "srv_enable": "true" }'
   check_rest_response "200 OK"
+
+  echo_test_title "Verify the iSCSI service is enabled"
+  rest_request "GET" "/services/services/iscsitarget/"
+  check_rest_response "200 OK" || return 1
+  ISCSISTATUS=$(cat ${RESTYOUT} | ${JSAWK} 'return this.srv_state')
+  echo "ISCSISTATUS: $ISCSISTATUS"
+  echo $ISCSISTATUS | grep -q 'RUNNING'
+  if [ $? -eq 0 ] ; then
+    echo_ok
+  else
+    echo_fail
+  fi
 
   # Now connect to iSCSI target
   echo_test_title "Connecting to iSCSI target"
@@ -89,6 +106,23 @@ iscsi_tests()
 
   echo_test_title "Disconnect all targets"
   rc_test "iscsictl -R -a" || return 1
+
+  # Disable the iSCSI service
+  echo_test_title "Disable iSCSI service"
+  rest_request "PUT" "/services/services/iscsitarget/" '{ "srv_enable": "false" }'
+  check_rest_response "200 OK"
+
+  echo_test_title "Verify the iSCSI service is disabled"
+  rest_request "GET" "/services/services/iscsitarget/"
+  check_rest_response "200 OK" || return 1
+  ISCSISTATUS=$(cat ${RESTYOUT} | ${JSAWK} 'return this.srv_state')
+  echo "ISCSISTATUS: $ISCSISTATUS"
+  echo $ISCSISTATUS | grep -q 'STOPPED'
+  if [ $? -eq 0 ] ; then
+    echo_ok
+  else
+    echo_fail
+  fi
 
 }
 
