Adding check to ssh tests for verifying that an ssh-agent is running.
* Modifies iscsi tests, changing the default target name.

diff --git a/freenas/9.10-tests/create/ssh b/freenas/9.10-tests/create/ssh
--- a/freenas/9.10-tests/create/ssh
+++ b/freenas/9.10-tests/create/ssh
@@ -31,10 +31,13 @@ ssh_tests()
   check_service_status "RUNNING"
 
   echo_test_title "Ensure that we have a running ssh-agent"
-  ssh-add -L 2>&1 | grep -q "Error connecting to agent" && echo_fail && return 1 || echo_ok
+  # Could not open a connection to your authentication agent.
+  ssh-add -L 2>&1 | \
+    grep -q -e "Error connecting to agent" -e "Could not open a connection to your authentication agent." \
+    && echo_fail && return 1 || echo_ok
 
   # Grab the path if an RSA key already exists and is ready to use
-  if ssh-add -L | grep -q "^ssh-rsa" ; then
+  if ssh-add -L 2>&1 | grep -q "^ssh-rsa" ; then
     ssh_keypath=$(ssh-add -L | awk '$1 == "ssh-rsa" {print $3}' | head -n 1)
   else
     if [ ! -f "${ssh_keypath}" -a -f "${HOME}/.ssh/id_rsa.tests" ] ; then
