Skip ssh-agent testing for now

diff --git a/freenas/9.10-tests/create/ssh b/freenas/9.10-tests/create/ssh
--- a/freenas/9.10-tests/create/ssh
+++ b/freenas/9.10-tests/create/ssh
@@ -30,26 +30,26 @@ ssh_tests()
   rest_request "GET" "/services/services/ssh/"
   check_service_status "RUNNING"
 
-  echo_test_title "Ensure that we have a running ssh-agent"
-  # Could not open a connection to your authentication agent.
-  ssh-add -L 2>&1 | \
-    grep -q -e "Error connecting to agent" -e "Could not open a connection to your authentication agent." \
-    && echo_fail && return 1 || echo_ok
+#  echo_test_title "Ensure that we have a running ssh-agent"
+#  # Could not open a connection to your authentication agent.
+#  ssh-add -L 2>&1 | \
+#    grep -q -e "Error connecting to agent" -e "Could not open a connection to your authentication agent." \
+#    && echo_fail && return 1 || echo_ok
 
-  # Grab the path if an RSA key already exists and is ready to use
-  if ssh-add -L 2>&1 | grep -q "^ssh-rsa" ; then
-    ssh_keypath=$(ssh-add -L | awk '$1 == "ssh-rsa" {print $3}' | head -n 1)
-  else
-    # Use id_rsa.tests key if it exists, otherwise use the id_rsa key
-    if [ -f "${HOME}/.ssh/id_rsa.tests" ] ; then
-      ssh_keypath="${HOME}/.ssh/id_rsa.tests"
-    elif [ ! -f "${ssh_keypath}" ] ; then
-      # Create the id_rsa key if it does not already exist
-      ssh-keygen -b 4096 -t rsa -q -N "" -f "${ssh_keypath}" >/dev/null 2>/dev/null
-    fi
-    # Add whichever key, id_rsa or id_rsa.tests to our ssh-agent
-    ssh-add "${ssh_keypath}" >/dev/null 2>/dev/null
-  fi
+#  # Grab the path if an RSA key already exists and is ready to use
+#  if ssh-add -L 2>&1 | grep -q "^ssh-rsa" ; then
+#    ssh_keypath=$(ssh-add -L | awk '$1 == "ssh-rsa" {print $3}' | head -n 1)
+#  else
+#    # Use id_rsa.tests key if it exists, otherwise use the id_rsa key
+#    if [ -f "${HOME}/.ssh/id_rsa.tests" ] ; then
+#      ssh_keypath="${HOME}/.ssh/id_rsa.tests"
+#    elif [ ! -f "${ssh_keypath}" ] ; then
+#      # Create the id_rsa key if it does not already exist
+#      ssh-keygen -b 4096 -t rsa -q -N "" -f "${ssh_keypath}" >/dev/null 2>/dev/null
+#    fi
+#    # Add whichever key, id_rsa or id_rsa.tests to our ssh-agent
+#    ssh-add "${ssh_keypath}" >/dev/null 2>/dev/null
+#  fi
 
   # Get the root user id so we can add ssh keys to the test target
   rest_request "GET" "/account/users/"
