Changing out OS X umount cmd for diskutil unmount
* Updates OS X tests to use diskutil unmount over umount cmd, as suggested by umount manpage
* Cleaning up requirements checking in osx tests.
* Updating test counts

diff --git a/freenas/9.10-tests/update/ad_osx b/freenas/9.10-tests/update/ad_osx
--- a/freenas/9.10-tests/update/ad_osx
+++ b/freenas/9.10-tests/update/ad_osx
@@ -11,31 +11,27 @@ export REQUIRES
 
 ad_osx_tests() 
 {
+  set_test_group_text "2 - Update - Active Directory OS X tests" "22"
+  CLASSNAME=ixbuild.resty.functional.update.ad_osx
+
   local DATASET="ad-osx"
   local SMB_NAME="TestShare"
   local SMB_PATH="/mnt/tank/${DATASET}"
   local MOUNTPOINT="/Volumes/${BRIDGEHOST}"
   local MP_GROUP="AD01\\qa"
 
-  TEST_CNT=11
-  if [ -n "${OSX_HOST}" -a -n "${BRIDGEIP}" ]; then
-    TEST_CNT=22
-
-    # Clean up any leftover items from previous failed SMB runs
-    osx_test -q "umount -f '${MOUNTPOINT}'; rmdir '${MOUNTPOINT}'; exit 0"
-  fi
-
-  set_test_group_text "2 - Update - Active Directory OS X tests" "${TEST_CNT}"
-  CLASSNAME=ixbuild.resty.functional.update.ad_osx
-
-  if [ -z "$ADUSERNAME" -o -z "$ADPASSWORD" ] ; then
-     echo -n "Missing the ADUSERNAME / ADPASSWORD settings, test skipped.."
-     echo_skipped
-     add_xml_result "skipped" "Skipped due to missing AD settings"
-     return 0
-  fi
+  local REQUIRED_SETTINGS=( "OSX_HOST" "OSX_USERNAME" "OSX_PASSWORD" "BRIDGEIP" "BRIDGEHOST" "ADUSERNAME" "ADPASSWORD" )
+  for SETTING in "${REQUIRED_SETTINGS[@]}"
+  do  
+    if [ -z "${!SETTING}" ]; then
+      echo -n "Required settings for ad_osx: '${REQUIRED_SETTINGS[*]}'; missing ${SETTING}"
+      echo_skipped
+      return 0
+    fi  
+  done
 
   # Clean up any leftover items from previous failed AD LDAP or SMB runs
+  osx_test -q "diskutil unmount force '${MOUNTPOINT}'; rmdir '${MOUNTPOINT}'; exit 0"
   rest_request "PUT" "/directoryservice/activedirectory/1/" '{ "ad_bindpw": "'${ADPASSWORD}'", "ad_bindname": "'${ADUSERNAME}'", "ad_domainname": "'${BRIDGEDOMAIN}'", "ad_netbiosname_a": "'${BRIDGEHOST}'", "ad_idmap_backend": "rid", "ad_enable":"false" }'
   rest_request "PUT" "/directoryservice/ldap/1/" '{ "ldap_basedn": "'${LDAPBASEDN}'", "ldap_binddn": "'${LDAPBINDDN}'",  "ldap_bindpw": "'${LDAPBINDPASSWORD}'", "ldap_netbiosname_a": "'${BRIDGEHOST}'", "ldap_hostname": "'${LDAPHOSTNAME}'", "ldap_has_samba_schema": true, "ldap_enable": false }'
   rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": false }'
@@ -90,40 +86,40 @@ ad_osx_tests()
   echo_test_title "Checking permissions on ${SMB_PATH}"
   check_dataset_group "${SMB_PATH}" "${MP_GROUP}" || return 1
 
-  if [ -n "${OSX_HOST}" -a -n "${BRIDGEIP}" ]; then
-    # Mount share on OSX system and create a test file
-    echo_test_title "Create mount-point for SMB on OSX system"
-    osx_test "mkdir -p '${MOUNTPOINT}' && sync" || return 1
+  # Mount share on OSX system and create a test file
+  echo_test_title "Create mount-point for SMB on OSX system"
+  osx_test "mkdir -p '${MOUNTPOINT}' && sync" || return 1
 
-    echo_test_title "Mount SMB share on OSX system"
-    osx_test "mount -t smbfs 'smb://aduser:12345678@${BRIDGEIP}/${SMB_NAME}' '${MOUNTPOINT}'" || return 1
+  echo_test_title "Mount SMB share on OSX system"
+  osx_test "mount -t smbfs 'smb://aduser:12345678@${BRIDGEIP}/${SMB_NAME}' '${MOUNTPOINT}'" || return 1
 
-    echo_test_title "Verify SMB share has been mounted on OSX"
-    # //{ADUSERNAME}@{FNASTESTIP}/{SMB_NAME} on {MOUNTPOINT} (smbfs, nodev, nosuid, mounted by jenkins)
-    wait_for_osx_mnt "${MOUNTPOINT}"
-    check_exit_status || return 1
+  echo_test_title "Verify SMB share has been mounted on OSX"
+  # //{ADUSERNAME}@{FNASTESTIP}/{SMB_NAME} on {MOUNTPOINT} (smbfs, nodev, nosuid, mounted by jenkins)
+  wait_for_osx_mnt "${MOUNTPOINT}"
+  check_exit_status || return 1
 
-    echo_test_title "Checking for ability to list files on volume"
-    osx_test "time ls -la ${MOUNTPOINT}" || return 1
+  echo_test_title "Checking for ability to list files on volume"
+  osx_test "time ls -la ${MOUNTPOINT}" || return 1
 
-    echo_test_title "Create file on SMB share via OSX to test permissions"
-    osx_test "touch '${MOUNTPOINT}/testfile.txt'" || return 1
+  echo_test_title "Create file on SMB share via OSX to test permissions"
+  osx_test "touch '${MOUNTPOINT}/testfile.txt'" || return 1
 
-    # Move test file to a new location on the SMB share
-    echo_test_title "Moving SMB test file into a new directory"
-    osx_test "mkdir -p '${MOUNTPOINT}/tmp' && mv '${MOUNTPOINT}/testfile.txt' '${MOUNTPOINT}/tmp/testfile.txt'" || return 1
+  # Move test file to a new location on the SMB share
+  echo_test_title "Moving SMB test file into a new directory"
+  osx_test "mkdir -p '${MOUNTPOINT}/tmp' && mv '${MOUNTPOINT}/testfile.txt' '${MOUNTPOINT}/tmp/testfile.txt'" || return 1
 
-    # Delete test file and test directory from SMB share
-    echo_test_title "Deleting test file and directory from SMB share"
-    osx_test "rm -f '${MOUNTPOINT}/tmp/testfile.txt' && rmdir '${MOUNTPOINT}/tmp'" || return 1
+  # Delete test file and test directory from SMB share
+  echo_test_title "Deleting test file and directory from SMB share"
+  osx_test "rm -f '${MOUNTPOINT}/tmp/testfile.txt' && rmdir '${MOUNTPOINT}/tmp'" || return 1
 
-    echo_test_title "Verifying that test file and directory were successfully removed"
-    osx_test "find -- '${MOUNTPOINT}/' -prune -type d -empty | grep -q ." || return 1
+  echo_test_title "Verifying that test file and directory were successfully removed"
+  osx_test "find -- '${MOUNTPOINT}/' -prune -type d -empty | grep -q ." || return 1
 
-    # Clean up mounted SMB share
-    echo_test_title "Unmount SMB share"
-    osx_test "umount -f '${MOUNTPOINT}'" || return 1
-  fi
+  # Clean up mounted SMB share
+  # OS X `umount` manpage reports that umount may fail often.
+  # "It is recommended that diskutil(1) (as in, ``diskutil unmount /mnt'') be used instead."
+  echo_test_title "Unmount SMB share"
+  osx_test "diskutil unmount force '${MOUNTPOINT}'" || return 1
 
   # Disable Active Directory Directory
   echo_test_title "Disabling Active Directory.."
diff --git a/freenas/9.10-tests/update/afp_osx b/freenas/9.10-tests/update/afp_osx
--- a/freenas/9.10-tests/update/afp_osx
+++ b/freenas/9.10-tests/update/afp_osx
@@ -11,29 +11,31 @@ export REQUIRES
 
 afp_osx_tests()
 {
+  # Set the group text and number of tests
+  set_test_group_text "2 - Update - AFP OS X tests" "21"
+  CLASSNAME=ixbuild.resty.functional.update.afp_osx
+
   local DATASET="afp-osx"
   local AFP_NAME="My AFP Share"
   local AFP_PATH="/mnt/tank/${DATASET}"
   local MOUNTPOINT="/Volumes/${BRIDGEHOST}"
   local MP_GROUP="wheel"
 
-  # Set the test count based on config settings
-  TEST_CNT="14"
-  if [ -n "${OSX_HOST}" -a -n "${BRIDGEIP}" ]; then
-    TEST_CNT="21"
-
-    # Clean up any leftover items from previous failed AFP runs
-    osx_test -q "umount -f '${MOUNTPOINT}'; rmdir '${MOUNTPOINT}'; exit 0"
-  fi
+  local REQUIRED_SETTINGS=( "OSX_HOST" "OSX_USERNAME" "OSX_PASSWORD" "BRIDGEIP" "BRIDGEHOST" )
+  for SETTING in "${REQUIRED_SETTINGS[@]}"
+  do  
+    if [ -z "${!SETTING}" ]; then
+      echo -n "Required settings for afp_osx: '${REQUIRED_SETTINGS[*]}'; missing ${SETTING}"
+      echo_skipped
+      return 0
+    fi  
+  done
 
   # Clean up any leftover items from previous failed runs
+  osx_test -q "diskutil unmount force \"${MOUNTPOINT}\"; rmdir \"${MOUNTPOINT}\"; exit 0"
   rest_request "PUT" "/services/afp/" '{ "afp_srv_guest": false }'
   rest_request "DELETE" "/sharing/afp/" '{ "afp_name": "'"${AFP_NAME}"'", "afp_path": "'"${APF_PATH}"'" }'
   rest_request "DELETE" "/storage/volume/1/datasets/${DATASET}/"
-
-  # Set the group text and number of tests
-  set_test_group_text "2 - Update - AFP OS X tests" "${TEST_CNT}"
-  CLASSNAME=ixbuild.resty.functional.update.afp_osx
 
   echo_test_title "Creating AFP dataset"
   rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "'"${DATASET}"'" }'
@@ -44,11 +46,7 @@ afp_osx_tests()
   check_rest_response "200" || return 1
 
   echo_test_title "Enabling AFP service"
-  if [ -n "${BRIDGEIP}" ]; then
-    rest_request "PUT" "/services/afp/" '{ "afp_srv_guest": true, "afp_srv_bindip": "'"${BRIDGEIP}"'" }'
-  else
-    rest_request "PUT" "/services/afp/" '{ "afp_srv_guest": true }'
-  fi
+  rest_request "PUT" "/services/afp/" '{ "afp_srv_guest": true, "afp_srv_bindip": "'"${BRIDGEIP}"'" }'
   check_rest_response "200 OK" || return 1
 
   # Now start the service
@@ -76,44 +74,44 @@ afp_osx_tests()
   check_dataset_group "${AFP_PATH}" "${MP_GROUP}" || return 1
 
   # Verify mountability and permissions of AFP share after config changes
-  if [ -n "${OSX_HOST}" -a -n "${BRIDGEIP}" ]; then
-    echo_test_title "Check to see if AFP can be accessed from OS X"
-    wait_for_afp_from_osx
-    check_exit_status || return 1
+  echo_test_title "Check to see if AFP can be accessed from OS X"
+  wait_for_afp_from_osx
+  check_exit_status || return 1
 
-    # Mount share on OSX system and create a test file
-    echo_test_title "Create mount-point for AFP on OSX system"
-    osx_test "mkdir -p '${MOUNTPOINT}' && sync" || return 1
-    sync
+  # Mount share on OSX system and create a test file
+  echo_test_title "Create mount-point for AFP on OSX system"
+  osx_test "mkdir -p '${MOUNTPOINT}' && sync" || return 1
+  sync
 
-    echo_test_title "Mount AFP share on OSX system"
-    osx_test "mount -t afp 'afp://${BRIDGEIP}/${AFP_NAME}' '${MOUNTPOINT}'" || return 1
+  echo_test_title "Mount AFP share on OSX system"
+  osx_test "mount -t afp 'afp://${BRIDGEIP}/${AFP_NAME}' '${MOUNTPOINT}'" || return 1
 
-    echo_test_title "Verify that AFP share has been mounted"
-    wait_for_osx_mnt "${MOUNTPOINT}"
-    check_exit_status || return 1
+  echo_test_title "Verify that AFP share has been mounted"
+  wait_for_osx_mnt "${MOUNTPOINT}"
+  check_exit_status || return 1
 
-    echo_test_title "Checking for ability to list files on ${MOUNTPOINT}"
-    osx_test "time ls -la ${MOUNTPOINT}" || return 1
+  echo_test_title "Checking for ability to list files on ${MOUNTPOINT}"
+  osx_test "time ls -la ${MOUNTPOINT}" || return 1
 
-    echo_test_title "Create file on AFP share via OSX to test permissions"
-    osx_test "touch '${MOUNTPOINT}/testfile.txt'" || return 1
+  echo_test_title "Create file on AFP share via OSX to test permissions"
+  osx_test "touch '${MOUNTPOINT}/testfile.txt'" || return 1
 
-    # Move test file to a new location on the AFP share
-    echo_test_title "Moving AFP test file into a new directory"
-    osx_test "mkdir -p '${MOUNTPOINT}/tmp' && mv '${MOUNTPOINT}/testfile.txt' '${MOUNTPOINT}/tmp/testfile.txt'" || return 1
+  # Move test file to a new location on the AFP share
+  echo_test_title "Moving AFP test file into a new directory"
+  osx_test "mkdir -p '${MOUNTPOINT}/tmp' && mv '${MOUNTPOINT}/testfile.txt' '${MOUNTPOINT}/tmp/testfile.txt'" || return 1
 
-    # Delete test file and test directory from AFP share
-    echo_test_title "Deleting test file and directory from AFP share"
-    osx_test "rm -f '${MOUNTPOINT}/tmp/testfile.txt' && rmdir '${MOUNTPOINT}/tmp'" || return 1
+  # Delete test file and test directory from AFP share
+  echo_test_title "Deleting test file and directory from AFP share"
+  osx_test "rm -f '${MOUNTPOINT}/tmp/testfile.txt' && rmdir '${MOUNTPOINT}/tmp'" || return 1
 
-    echo_test_title "Verifying that test file and directory were successfully removed"
-    osx_test "find -- '${MOUNTPOINT}/' -prune -type d -empty | grep -q ." || return 1
+  echo_test_title "Verifying that test file and directory were successfully removed"
+  osx_test "find -- '${MOUNTPOINT}/' -prune -type d -empty | grep -q ." || return 1
 
-    # Clean up mounted AFP share
-    echo_test_title "Unmount AFP share"
-    osx_test "umount -f '${MOUNTPOINT}'" || return 1
-  fi
+  # Clean up mounted AFP share
+  # OS X `umount` manpage reports that umount may fail often.
+  # "It is recommended that diskutil(1) (as in, ``diskutil unmount /mnt'') be used instead."
+  echo_test_title "Unmount AFP share"
+  osx_test "diskutil unmount force '${MOUNTPOINT}'" || return 1
 
   # Test disable AFP
   echo_test_title "Verify AFP service can be disabled.."
diff --git a/freenas/9.10-tests/update/ldap_osx b/freenas/9.10-tests/update/ldap_osx
--- a/freenas/9.10-tests/update/ldap_osx
+++ b/freenas/9.10-tests/update/ldap_osx
@@ -11,6 +11,9 @@ export REQUIRES
 
 ldap_osx_tests() 
 {
+  set_test_group_text "2 - Update - LDAP OS X tests" "25"
+  CLASSNAME=ixbuild.resty.functional.update.ldap_osx
+
   local DATASET="ldap-osx"
   local SMB_NAME="TestShare"
   local SMB_PATH="/mnt/tank/${DATASET}"
@@ -20,25 +23,21 @@ ldap_osx_tests()
   local LDAP_PASS="12345678"
   local MP_GROUP="qa"
 
-  set_test_group_text "2 - Update - LDAP OS X tests" "25"
-  CLASSNAME=ixbuild.resty.functional.update.ldap_osx
-
-  if [ -z "$LDAPBINDDN" -o -z "$LDAPBINDPASSWORD" -o -z "$OSX_HOST" -o -z "$BRIDGEIP" -o -z "$ADUSERNAME" ] ; then
-    echo -n "Missing required settings for LDAP, Active Directory, test skipped.."
-    echo_skipped
-    add_xml_result "skipped" "Skipped due to missing LDAP settings"
-    return 0
-  fi  
-
-  if [ -z "$LDAPBINDDN2" -o -z "$LDAPBINDPASSWORD2" ] ; then
-     echo -n "Missing the LDAPBINDDN2 / LDAPBINDPASSWORD2 settings, test skipped.."
-     echo_skipped
-     add_xml_result "skipped" "Skipped due to missing LDAP settings"
-     return 0
-  fi
+  local REQUIRED_SETTINGS=( \
+    "OSX_HOST" "OSX_USERNAME" "OSX_PASSWORD" "BRIDGEIP" "BRIDGEHOST" \
+    "ADUSERNAME" "ADPASSWORD" "LDAPBINDDN" "LDAPBINDPASSWORD" "LDAPBINDDN2" "LDAPBINDPASSWORD2" \
+  )
+  for SETTING in "${REQUIRED_SETTINGS[@]}"
+  do  
+    if [ -z "${!SETTING}" ]; then
+      echo -n "Required settings for ldap_osx: '${REQUIRED_SETTINGS[*]}'; missing ${SETTING}"
+      echo_skipped
+      return 0
+    fi  
+  done
 
   # Clean up any leftover items from previous failed AD LDAP or SMB runs
-  osx_test -q "umount -f '${MOUNTPOINT}'; rmdir '${MOUNTPOINT}'; exit 0"
+  osx_test -q "diskutil unmount force \"${MOUNTPOINT}\"; rmdir \"${MOUNTPOINT}\"; exit 0"
   rest_request "PUT" "/directoryservice/activedirectory/1/" '{ "ad_bindpw": "'${ADPASSWORD}'", "ad_bindname": "'${ADUSERNAME}'", "ad_domainname": "'${BRIDGEDOMAIN}'", "ad_netbiosname_a": "'${BRIDGEHOST}'", "ad_idmap_backend": "rid", "ad_enable":"false" }'
   rest_request "PUT" "/directoryservice/ldap/1/" '{ "ldap_basedn": "'${LDAPBASEDN}'", "ldap_anonbind": false, "ldap_netbiosname_a": "'${BRIDGEHOST}'", "ldap_hostname": "'${LDAPHOSTNAME}'", "ldap_has_samba_schema": true, "ldap_enable": false }'
   rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": false }'
@@ -122,8 +121,10 @@ ldap_osx_tests()
     osx_test "find -- '${MOUNTPOINT}/' -prune -type d -empty | grep -q ." || return 1
 
     # Clean up mounted SMB share
+    # OS X `umount` manpage reports that umount may fail often.
+    # "It is recommended that diskutil(1) (as in, ``diskutil unmount /mnt'') be used instead."
     echo_test_title "Unmount SMB share"
-    osx_test "umount -f '${MOUNTPOINT}'" || return 1
+    osx_test "diskutil unmount force '${MOUNTPOINT}'" || return 1
   fi
 
   # Disable LDAP
diff --git a/freenas/9.10-tests/update/nfs_osx b/freenas/9.10-tests/update/nfs_osx
--- a/freenas/9.10-tests/update/nfs_osx
+++ b/freenas/9.10-tests/update/nfs_osx
@@ -11,6 +11,10 @@ export REQUIRES
 
 nfs_osx_tests()
 {
+  # Set the group text and number of tests
+  set_test_group_text "1 - Update - NFS OSX tests" "33"
+  CLASSNAME=ixbuild.resty.functional.create.nfs_osx
+
   local DATASET="nfs-osx"
   local NFS_PATH="/mnt/tank/${DATASET}"
   local MOUNTPOINT="/Volumes/${BRIDGEHOST}"
@@ -18,21 +22,21 @@ nfs_osx_tests()
   local NFS_PORT=618
   local MP_GROUP="wheel"
 
-  if [ -z "$OSX_HOST" -o -z "${BRIDGEIP}" -o -z "${BRIDGEHOST}" ]; then
-    echo "OSX_HOST, BRIDGEIP and BRIDGEHOST settings required for NFS OSX tests"
-    echo_skipped
-    return 0
-  fi
-
-  # Set the group text and number of tests
-  set_test_group_text "1 - Update - NFS OSX tests" "33"
-  CLASSNAME=ixbuild.resty.functional.create.nfs_osx
+  local REQUIRED_SETTINGS=( "OSX_HOST" "OSX_USERNAME" "OSX_PASSWORD" "BRIDGEIP" "BRIDGEHOST" )
+  for SETTING in "${REQUIRED_SETTINGS[@]}"
+  do  
+    if [ -z "${!SETTING}" ]; then
+      echo -n "Required settings for nfs_osx: '${REQUIRED_SETTINGS[*]}'; missing ${SETTING}"
+      echo_skipped
+      return 0
+    fi  
+  done
 
   # Clean up any leftover items from previous failed NFS runs
+  osx_test -q "diskutil unmount force \"${MOUNTPOINT}\"; rmdir \"${MOUNTPOINT}\"; exit 0"
   rest_request "DELETE" "/sharing/nfs/" '{ "nfs_comment": "My Test Share", "nfs_paths": ["'"${NFS_PATH}"'"], "nfs_security": "sys" }'
   rest_request "DELETE" "/storage/volume/1/datasets/${DATASET}/"
   rest_request "PUT" "/services/services/nfs/" '{ "srv_enable": false }'
-  osx_test -q "umount -f \"${MOUNTPOINT}\"; rmdir \"${MOUNTPOINT}\"; exit 0"
 
   # Create a dataset to use with NFS
   echo_test_title "Creating dataset ${DATASET}"
@@ -135,8 +139,11 @@ nfs_osx_tests()
   echo_test_title "Verify that test file and directory were successfully removed"
   osx_test "find -- \"${MOUNTPOINT}/\" -prune -type d -empty | grep -q ." || return 1
 
+  # Clean up mounted NFS share
+  # OS X `umount` manpage reports that umount may fail often.
+  # "It is recommended that diskutil(1) (as in, ``diskutil unmount /mnt'') be used instead."
   echo_test_title "Unmount NFS share"
-  osx_test "umount -f \"${MOUNTPOINT}\""
+  osx_test "diskutil unmount force '${MOUNTPOINT}'" || return 1
 
   echo_test_title "Removing NFS share on ${NFS_PATH}"
   rest_request "DELETE" "/sharing/nfs/" '{ "nfs_comment": "My Test Share", "nfs_paths": ["'"${NFS_PATH}"'"], "nfs_security": "sys" }'
diff --git a/freenas/9.10-tests/update/smb_osx b/freenas/9.10-tests/update/smb_osx
--- a/freenas/9.10-tests/update/smb_osx
+++ b/freenas/9.10-tests/update/smb_osx
@@ -11,25 +11,28 @@ export REQUIRES
 
 smb_osx_tests()
 {
+  # Set the group text and number of tests
+  set_test_group_text "2 - Update - Samba OS X tests" "22"
+  CLASSNAME=ixbuild.resty.functional.update.smb_osx
+
   local DATASET="smb-osx"
   local SMB_NAME="TestShare"
   local SMB_PATH="/mnt/tank/${DATASET}"
   local MOUNTPOINT="/Volumes/${BRIDGEHOST}"
   local MP_GROUP="wheel"
 
-  TEST_CNT=11
-  if [ -n "${OSX_HOST}" -a -n "${BRIDGEIP}" ]; then
-    TEST_CNT=22
-
-    # Clean up any leftover items from previous failed SMB runs
-    osx_test -q "umount -f '${MOUNTPOINT}'; rmdir '${MOUNTPOINT}'; exit 0"
-  fi
-
-  # Set the group text and number of tests
-  set_test_group_text "2 - Update - Samba OS X tests" "${TEST_CNT}"
-  CLASSNAME=ixbuild.resty.functional.update.smb_osx
+  local REQUIRED_SETTINGS=( "OSX_HOST" "OSX_USERNAME" "OSX_PASSWORD" "BRIDGEIP" "BRIDGEHOST" "BRIDGEDOMAIN" "ADUSERNAME" "ADPASSWORD" )
+  for SETTING in "${REQUIRED_SETTINGS[@]}"
+  do  
+    if [ -z "${!SETTING}" ]; then
+      echo -n "Required settings for afp_osx: '${REQUIRED_SETTINGS[*]}'; missing ${SETTING}"
+      echo_skipped
+      return 0
+    fi  
+  done
 
   # Clean up any leftover items from previous failed AD LDAP or SMB runs
+  osx_test -q "diskutil unmount force \"${MOUNTPOINT}\"; rmdir \"${MOUNTPOINT}\"; exit 0"
   rest_request "PUT" "/directoryservice/activedirectory/1/" '{ "ad_bindpw": "'${ADPASSWORD}'", "ad_bindname": "'${ADUSERNAME}'", "ad_domainname": "'${BRIDGEDOMAIN}'", "ad_netbiosname_a": "'${BRIDGEHOST}'", "ad_idmap_backend": "rid", "ad_enable":"false" }'
   rest_request "PUT" "/directoryservice/ldap/1/" '{ "ldap_basedn": "'${LDAPBASEDN}'", "ldap_binddn": "'${LDAPBINDDN}'",  "ldap_bindpw": "'${LDAPBINDPASSWORD}'", "ldap_netbiosname_a": "'${BRIDGEHOST}'", "ldap_hostname": "'${LDAPHOSTNAME}'", "ldap_has_samba_schema": true, "ldap_enable": false }'
   rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": false }'
@@ -103,8 +106,10 @@ smb_osx_tests()
     osx_test "find -- '${MOUNTPOINT}/' -prune -type d -empty | grep -q ." || return 1
 
     # Clean up mounted SMB share
+    # OS X `umount` manpage reports that umount may fail often.
+    # "It is recommended that diskutil(1) (as in, ``diskutil unmount /mnt'') be used instead."
     echo_test_title "Unmount SMB share"
-    osx_test "umount -f '${MOUNTPOINT}'" || return 1
+    osx_test "diskutil unmount force '${MOUNTPOINT}'" || return 1
   fi  
 
   echo_test_title "Removing SMB share on ${SMB_PATH}"
