Propagating directory permission checks across smb & afp tests (bsd & osx)

diff --git a/freenas/9.10-tests/update/ldap_osx b/freenas/9.10-tests/update/ldap_osx
--- a/freenas/9.10-tests/update/ldap_osx
+++ b/freenas/9.10-tests/update/ldap_osx
@@ -18,16 +18,15 @@ ldap_osx_tests()
   local LDAP_USER="ldapuser"
   local LDAP_PASS="12345678"
 
-  TEST_CNT=14
-  if [ -n "${OSX_HOST}" -a -n "${BRIDGEIP}" ]; then
-    TEST_CNT=21
-
-    # Clean up any leftover items from previous failed SMB runs
-    osx_test "umount -f '${MOUNTPOINT}'; rmdir '${MOUNTPOINT}'; exit 0"
-  fi
-
-  set_test_group_text "2 - Update - LDAP OS X tests" "${TEST_CNT}"
+  set_test_group_text "2 - Update - LDAP OS X tests" "25"
   CLASSNAME=ixbuild.resty.functional.update.ldap_osx
+
+  if [ -z "$LDAPBINDDN" -o -z "$LDAPBINDPASSWORD" -o -z "$OSX_HOST" -o -z "$BRIDGEIP" -o -z "$ADUSERNAME" ] ; then
+    echo -n "Missing required settings for LDAP, Active Directory, test skipped.."
+    echo_skipped
+    add_xml_result "skipped" "Skipped due to missing LDAP settings"
+    return 0
+  fi  
 
   if [ -z "$LDAPBINDDN2" -o -z "$LDAPBINDPASSWORD2" ] ; then
      echo -n "Missing the LDAPBINDDN2 / LDAPBINDPASSWORD2 settings, test skipped.."
@@ -37,6 +36,7 @@ ldap_osx_tests()
   fi
 
   # Clean up any leftover items from previous failed AD LDAP or SMB runs
+  osx_test "umount -f '${MOUNTPOINT}'; rmdir '${MOUNTPOINT}'; exit 0"
   rest_request "PUT" "/directoryservice/activedirectory/1/" '{ "ad_bindpw": "'${ADPASSWORD}'", "ad_bindname": "'${ADUSERNAME}'", "ad_domainname": "'${BRIDGEDOMAIN}'", "ad_netbiosname_a": "'${BRIDGEHOST}'", "ad_idmap_backend": "rid", "ad_enable":"false" }'
   rest_request "PUT" "/directoryservice/ldap/1/" '{ "ldap_basedn": "'${LDAPBASEDN}'", "ldap_anonbind": false, "ldap_netbiosname_a": "'${BRIDGEHOST}'", "ldap_hostname": "'${LDAPHOSTNAME}'", "ldap_has_samba_schema": true, "ldap_enable": false }'
   rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": false }'
@@ -50,12 +50,12 @@ ldap_osx_tests()
 
   echo_test_title "Creating SMB dataset"
   rest_request "POST" "/storage/volume/tank/datasets/" '{ "name": "'"${DATASET}"'" }'
-  check_rest_response "201 Created"  
+  check_rest_response "201 Created" || return 1
 
   # Enable LDAP
   echo_test_title "Enabling LDAP.."
   rest_request "PUT" "/directoryservice/ldap/1/" '{ "ldap_basedn": "'${LDAPBASEDN2}'", "ldap_binddn": "'${LDAPBINDDN2}'", "ldap_bindpw": "'${LDAPBINDPASSWORD2}'", "ldap_netbiosname_a": "'${BRIDGEHOST}'", "ldap_hostname": "'${LDAPHOSTNAME2}'", "ldap_has_samba_schema": true, "ldap_enable": true }'
-  check_rest_response "200 OK"
+  check_rest_response "200 OK" || return 1
 
   # Check LDAP
   echo_test_title "Checking LDAP.."
@@ -64,24 +64,33 @@ ldap_osx_tests()
 
   echo_test_title "Enabling SMB service"
   rest_request "PUT" "/services/cifs/" '{ "cifs_srv_description": "Test FreeNAS Server", "cifs_srv_guest": "nobody", "cifs_hostname_lookup": false, "cifs_srv_aio_enable": false }'
-  check_rest_response "200 OK"
+  check_rest_response "200 OK" || return 1
 
   # Now start the service
   echo_test_title "Starting SMB service"
   rest_request "PUT" "/services/services/cifs/" '{ "srv_enable": true }'
-  check_rest_response "200 OK"
+  check_rest_response "200 OK" || return 1
+
+  echo_test_title "Verifying that SMB service has started"
+  wait_for_avail_port "445"
+  check_exit_status || return 1
 
   echo_test_title "Checking to see if SMB service is enabled"
   rest_request "GET" "/services/services/cifs/"
-  check_service_status "RUNNING"
+  check_service_status "RUNNING" || return 1
 
   echo_test_title "Changing permissions on ${SMB_PATH}"
   rest_request "PUT" "/storage/permission/" '{ "mp_path": "'"${SMB_PATH}"'", "mp_acl": "unix", "mp_mode": "777", "mp_user": "root", "mp_group": "qa", "mp_recursive": true }'
-  check_rest_response "201 Created"   
+  check_rest_response "201 Created"
 
   echo_test_title "Creating a SMB share on ${SMB_PATH}"
   rest_request "POST" "/sharing/cifs/" '{ "cfs_comment": "My Test SMB Share", "cifs_path": "'"${SMB_PATH}"'", "cifs_name": "'"${SMB_NAME}"'", "cifs_guestok": true, "cifs_vfsobjects": "streams_xattr" }'
-  check_rest_response "201 Created"
+  check_rest_response "201 Created" || return 1
+
+  local vol_name=$(dirname "${SMB_PATH}")
+  echo_test_title "Checking permissions on ${SMB_NAME}"
+  ssh_test "ls -la '${vol_name}' | awk '\$4 == \"${VOL_GROUP}\" && \$9 == \"${DATASET}\" ' "
+  check_exit_status || return 1   
 
   if [ -n "${OSX_HOST}" -a -n "${BRIDGEIP}" ]; then
     # Mount share on OSX system and create a test file
@@ -91,6 +100,15 @@ ldap_osx_tests()
 
     echo_test_title "Mount SMB share on OSX system"
     osx_test "mount -t smbfs 'smb://${LDAP_USER}:${LDAP_PASS}@${BRIDGEIP}/${SMB_NAME}' '${MOUNTPOINT}'"
+    check_exit_status || return 1
+
+    echo_test_title "Verify SMB share mounted on OSX system"
+    wait_for_osx_mnt "${MOUNTPOINT}"
+    check_exit_status || return 1
+
+    local device_name=`dirname "${MOUNTPOINT}"`
+    echo_test_title "Checking permissions on ${device_name}"
+    osx_test "time ls -la '${device_name}' | awk '\$4 == \"${VOL_GROUP}\" && \$9 == \"${DATASET}\" ' "
     check_exit_status || return 1
 
     echo_test_title "Create file on SMB share via OSX to test permissions"
